import { Gift } from '../types';

export const GIFTS_DATA: Gift[] = [
  {
    id: '1',
    name: 'Difusor de aromas',
    description: 'Para deixar nossa casa com um perfume especial',
    category: 'Outros',
    totalAmount: 250,
    currentAmount: 0,
    imageUrl: '/img/Difusor de aromas.png',
  },
  {
    id: '2',
    name: 'Ferro de Passar',
    description: 'Praticidade no dia a dia',
    category: 'Eletrodomésticos',
    totalAmount: 250,
    currentAmount: 0,
    imageUrl: '/img/Ferro de Passar.png',
  },
  {
    id: '3',
    name: 'Jogo de taças para vinho',
    description: 'Para brindar os momentos especiais',
    category: 'Cozinha',
    totalAmount: 270,
    currentAmount: 0,
    imageUrl: '/img/Jogo de taças para vinho.png',
  },
  {
    id: '4',
    name: 'Toalha Banhão',
    description: 'Para o nosso enxoval de banho',
    category: 'Cama e Banho',
    totalAmount: 270,
    currentAmount: 0,
    imageUrl: '/img/Toalha Banhão.png',
  },
  {
    id: '5',
    name: 'Copo para Whiski',
    description: 'Para momentos de celebração',
    category: 'Cozinha',
    totalAmount: 280,
    currentAmount: 0,
    imageUrl: '/img/Copo para Whiski.png',
  },
  {
    id: '6',
    name: 'Taças para Champagne',
    description: 'Para brindar o nosso amor',
    category: 'Cozinha',
    totalAmount: 280,
    currentAmount: 0,
    imageUrl: '/img/Taças para Champagne.png',
  },
  {
    id: '7',
    name: 'Taças para cerveja Ruvolo',
    description: 'Para os encontros com amigos',
    category: 'Cozinha',
    totalAmount: 300,
    currentAmount: 0,
    imageUrl: '/img/Taças para cerveja Ruvolo.png',
  },
  {
    id: '8',
    name: 'Vale Pizza',
    description: 'Para aquela noite especial de pizza',
    category: 'Experiências',
    totalAmount: 300,
    currentAmount: 0,
    imageUrl: '/img/Vale Pizza.png',
  },
  {
    id: '9',
    name: 'Sanduicheira',
    description: 'Lanches rápidos e saborosos',
    category: 'Eletrodomésticos',
    totalAmount: 360,
    currentAmount: 0,
    imageUrl: '/img/Sanduicheira.png',
  },
  {
    id: '10',
    name: 'Panela de Pressão inox',
    description: 'Essencial para a nossa cozinha',
    category: 'Cozinha',
    totalAmount: 390,
    currentAmount: 0,
    imageUrl: '/img/Panela de Pressão inox.png',
  },
  {
    id: '11',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel dos sonhos',
    category: 'Experiências',
    totalAmount: 400,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '12',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel dos sonhos',
    category: 'Experiências',
    totalAmount: 400,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '13',
    name: 'Colcha microfibra queen',
    description: 'Conforto e maciez para a nossa cama',
    category: 'Cama e Banho',
    totalAmount: 420,
    currentAmount: 0,
    imageUrl: '/img/Colcha microfibra queen.png',
  },
  {
    id: '14',
    name: 'Cura ressaca do noivo',
    description: 'Kit essencial para o pós-festa!',
    category: 'Experiências',
    totalAmount: 440,
    currentAmount: 0,
    imageUrl: '/img/Cura ressaca do noivo.png',
  },
  {
    id: '15',
    name: 'Caldeirão Inox',
    description: 'Para receitas incríveis em família',
    category: 'Cozinha',
    totalAmount: 450,
    currentAmount: 0,
    imageUrl: '/img/Caldeirão Inox.png',
  },
  {
    id: '16',
    name: 'Smart speaker',
    description: 'Para ouvir nossas músicas preferidas',
    category: 'Outros',
    totalAmount: 450,
    currentAmount: 0,
    imageUrl: '/img/Smart speaker.png',
  },
  {
    id: '17',
    name: 'Conjunto de facas special CUT',
    description: 'Cortes precisos para nossas receitas',
    category: 'Cozinha',
    totalAmount: 465,
    currentAmount: 0,
    imageUrl: '/img/Conjunto de facas special CUT.png',
  },
  {
    id: '18',
    name: 'Faqueiro Inox 48 peças',
    description: 'Elegância para a nossa mesa',
    category: 'Cozinha',
    totalAmount: 469,
    currentAmount: 0,
    imageUrl: '/img/Faqueirox Inox 48 peças.png',
  },
  {
    id: '19',
    name: 'Aspirador de pó vertical',
    description: 'Praticidade na limpeza da casa',
    category: 'Eletrodomésticos',
    totalAmount: 480,
    currentAmount: 0,
    imageUrl: '/img/Aspirador de pó vertical.png',
  },
  {
    id: '20',
    name: 'Processador de Alimentos',
    description: 'Facilidade no preparo das refeições',
    category: 'Eletrodomésticos',
    totalAmount: 480,
    currentAmount: 0,
    imageUrl: '/img/Processador de Alimentos.png',
  },
  {
    id: '21',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa viagem inesquecível',
    category: 'Experiências',
    totalAmount: 500,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '22',
    name: 'Fritadeira Elétrica 7,5l',
    description: 'Receitas mais saudáveis e práticas',
    category: 'Eletrodomésticos',
    totalAmount: 500,
    currentAmount: 0,
    imageUrl: '/img/Fritadeira Elétrica 7,5l.png',
  },
  {
    id: '23',
    name: 'Jogo de lençois - queen',
    description: 'Para noites aconchegantes',
    category: 'Cama e Banho',
    totalAmount: 500,
    currentAmount: 0,
    imageUrl: '/img/Jogo de lençois - queen.png',
  },
  {
    id: '24',
    name: 'Roupão de banho',
    description: 'Para momentos de relaxamento',
    category: 'Cama e Banho',
    totalAmount: 500,
    currentAmount: 0,
    imageUrl: '/img/Roupão de banho.png',
  },
  {
    id: '25',
    name: 'Travesseiros',
    description: 'Conforto para nosso descanso',
    category: 'Cama e Banho',
    totalAmount: 500,
    currentAmount: 0,
    imageUrl: '/img/Travesseiros.png',
  },
  {
    id: '26',
    name: 'Cotas LUA DE MEL',
    description: 'Para um jantar especial a dois',
    category: 'Experiências',
    totalAmount: 500,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '27',
    name: 'Cotas LUA DE MEL',
    description: 'Para celebrar momentos a dois',
    category: 'Experiências',
    totalAmount: 500,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '28',
    name: 'Aparelho de Fondue',
    description: 'Para noites frias e românticas',
    category: 'Cozinha',
    totalAmount: 530,
    currentAmount: 0,
    imageUrl: '/img/Aparelho de Fundue.png',
  },
  {
    id: '29',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 550,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '30',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 550,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '31',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 550,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '32',
    name: 'Escorredor de louças',
    description: 'Organização e praticidade na bancada',
    category: 'Outros',
    totalAmount: 550,
    currentAmount: 0,
    imageUrl: '/img/Escorredor de louças.png',
  },
  {
    id: '33',
    name: 'Kit de facas Churrasco',
    description: 'Para os nossos churrascos em família',
    category: 'Cozinha',
    totalAmount: 550,
    currentAmount: 0,
    imageUrl: '/img/Kit de facas Churrasco.png',
  },
  {
    id: '34',
    name: 'Panela de pressão elétrica',
    description: 'Rapidez e segurança no cozimento',
    category: 'Eletrodomésticos',
    totalAmount: 580,
    currentAmount: 0,
    imageUrl: '/img/Panela de pressão elétrica.png',
  },
  {
    id: '35',
    name: 'Cafeteira Vertuo POP',
    description: 'Para começar o dia com o melhor café',
    category: 'Cozinha',
    totalAmount: 590,
    currentAmount: 0,
    imageUrl: '/img/Cafeteira Vertuo POP.png',
  },
  {
    id: '36',
    name: 'Liquidificador',
    description: 'Para sucos, vitaminas e receitas',
    category: 'Eletrodomésticos',
    totalAmount: 590,
    currentAmount: 0,
    imageUrl: '/img/Liquidificador.png',
  },
  {
    id: '37',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 600,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '38',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 600,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '39',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 600,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '40',
    name: 'Microondas 21l',
    description: 'Agilidade e praticidade no dia a dia',
    category: 'Eletrodomésticos',
    totalAmount: 600,
    currentAmount: 0,
    imageUrl: '/img/Microondas 21l.png',
  },
  {
    id: '41',
    name: 'Purificador de água',
    description: 'Água pura e fresca para nossa casa',
    category: 'Eletrodomésticos',
    totalAmount: 600,
    currentAmount: 0,
    imageUrl: '/img/Purificador de água.png',
  },
  {
    id: '42',
    name: 'Batedeira planetária',
    description: 'Para bolos e pães perfeitos',
    category: 'Eletrodomésticos',
    totalAmount: 625,
    currentAmount: 0,
    imageUrl: '/img/Batedeira planetária.png',
  },
  {
    id: '43',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa viagem',
    category: 'Experiências',
    totalAmount: 650,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '44',
    name: 'Cooktop vidro 4 bocas',
    description: 'Moderneza e estilo para a nossa cozinha',
    category: 'Cozinha',
    totalAmount: 660,
    currentAmount: 0,
    imageUrl: '/img/Cooktop vidro 4 bocas.png',
  },
  {
    id: '45',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa viagem inesquecível',
    category: 'Experiências',
    totalAmount: 700,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '46',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa viagem inesquecível',
    category: 'Experiências',
    totalAmount: 700,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '47',
    name: 'Conjunto de panelas inox',
    description: 'Qualidade e elegância para nossas receitas',
    category: 'Cozinha',
    totalAmount: 750,
    currentAmount: 0,
    imageUrl: '/img/Conjunto de Panelas inox.png',
  },
  {
    id: '48',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 750,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '49',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 800,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '50',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 800,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '51',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 800,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '52',
    name: 'Edredom Queen',
    description: 'Para noites bem aquecidas e confortáveis',
    category: 'Cama e Banho',
    totalAmount: 800,
    currentAmount: 0,
    imageUrl: '/img/Edredom Queen.png',
  },
  {
    id: '53',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição especial para nossa viagem',
    category: 'Experiências',
    totalAmount: 900,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '54',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição especial para nossa viagem',
    category: 'Experiências',
    totalAmount: 900,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '55',
    name: 'Chopeira',
    description: 'Para nossos momentos de lazer e encontros',
    category: 'Eletrodomésticos',
    totalAmount: 949,
    currentAmount: 0,
    imageUrl: '/img/Chopeira.png',
  },
  {
    id: '56',
    name: 'Mala para viagem',
    description: 'Para acompanharmos em nossas aventuras',
    category: 'Experiências',
    totalAmount: 1000,
    currentAmount: 0,
    imageUrl: '/img/Mala para viagem.png',
  },
  {
    id: '57',
    name: 'Persiana',
    description: 'Para aconchego e estilo em nossa casa',
    category: 'Outros',
    totalAmount: 1200,
    currentAmount: 0,
    imageUrl: '/img/Persiana.png',
  },
  {
    id: '58',
    name: 'Aparelho de Jantar',
    description: 'Para receber os amigos com elegância',
    category: 'Cozinha',
    totalAmount: 1400,
    currentAmount: 0,
    imageUrl: '/img/Aparelho de Jantar.png',
  },
  {
    id: '59',
    name: 'Robo aspirador de Pó',
    description: 'Praticidade para manter a casa limpa',
    category: 'Eletrodomésticos',
    totalAmount: 1500,
    currentAmount: 0,
    imageUrl: '/img/Robo aspirador de Pó.png',
  },
  {
    id: '60',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição especial para a nossa lua de mel dos sonhos',
    category: 'Experiências',
    totalAmount: 1621,
    currentAmount: 0,
    imageUrl: '/img/Cotas LUA DE MEL.png',
  },
  {
    id: '61',
    name: 'Home Theater',
    description: 'Para o nosso cinema em casa',
    category: 'Outros',
    totalAmount: 1630,
    currentAmount: 0,
    imageUrl: '/img/Home Theater.png',
  },
  {
    id: '62',
    name: 'Lava louças',
    description: 'Mais tempo juntos e menos louça',
    category: 'Eletrodomésticos',
    totalAmount: 1690,
    currentAmount: 0,
    imageUrl: '/img/Lava louças.png',
  },
  {
    id: '63',
    name: 'Cervejeira',
    description: 'Bebidas trincando de geladas para as festas',
    category: 'Eletrodomésticos',
    totalAmount: 1850,
    currentAmount: 0,
    imageUrl: '/img/Cervejeira.png',
  },
  {
    id: '64',
    name: 'Forno de Embutir elétrico',
    description: 'Para nossos assados e jantares',
    category: 'Eletrodomésticos',
    totalAmount: 2000,
    currentAmount: 0,
    imageUrl: '/img/Forno de Embutir elétrico.png',
  },
  {
    id: '65',
    name: 'Jbl boombox',
    description: 'Som de alta qualidade para as nossas festas',
    category: 'Outros',
    totalAmount: 2200,
    currentAmount: 0,
    imageUrl: '/img/Jbl boombox.png',
  },
  {
    id: '66',
    name: 'Ar-condicionado',
    description: 'Climatização perfeita para o nosso quarto',
    category: 'Eletrodomésticos',
    totalAmount: 2250,
    currentAmount: 0,
    imageUrl: '/img/Ar-condicionado.png',
  },
  {
    id: '67',
    name: 'Smart TV 55 polegadas',
    description: 'Para maratonar nossas séries favoritas',
    category: 'Outros',
    totalAmount: 2500,
    currentAmount: 0,
    imageUrl: '/img/Smart TV 55 polegadas.png',
  },
  {
    id: '68',
    name: 'Mesa de Jantar',
    description: 'Para reunir a família nas refeições',
    category: 'Outros',
    totalAmount: 2800,
    currentAmount: 0,
    imageUrl: '/img/Mesa de Jantar.png',
  },
  {
    id: '69',
    name: 'Cama Queen',
    description: 'Para o nosso descanso dos sonhos',
    category: 'Cama e Banho',
    totalAmount: 3400,
    currentAmount: 0,
    imageUrl: '/img/Cama Queen.png',
  },
  {
    id: '70',
    name: 'Sofa',
    description: 'Conforto e estilo para nossa sala de estar',
    category: 'Outros',
    totalAmount: 3500,
    currentAmount: 0,
    imageUrl: '/img/Sofa.png',
  },
  {
    id: '71',
    name: 'Geladeira',
    description: 'Essencial e espaçosa para nossa cozinha',
    category: 'Eletrodomésticos',
    totalAmount: 4100,
    currentAmount: 0,
    imageUrl: '/img/Geladeira.png',
  },
  {
    id: '72',
    name: 'Maquina Lava e Seca',
    description: 'Tecnologia e eficiência para nossas roupas',
    category: 'Eletrodomésticos',
    totalAmount: 5000,
    currentAmount: 0,
    imageUrl: '/img/Maquina Lava e Seca.png',
  }
];
