import { Gift } from '../types';

export const GIFTS_DATA: Gift[] = [
  {
    id: '1',
    name: 'Jogo 6 taças de vidro Bistro',
    description: 'Para brindarmos com nossos convidados.',
    category: 'Cozinha',
    totalAmount: 100,
    currentAmount: 0,
    imageUrl: '/img/1.jpg',
  },
  {
    id: '2',
    name: 'Fritadeira Elétrica Arno 7.5L Air Fryer',
    description: 'Praticidade para as nossas refeições diárias.',
    category: 'Eletrodomésticos',
    totalAmount: 500,
    currentAmount: 0,
    imageUrl: '/img/2.jpg',
  },
  {
    id: '3',
    name: 'Liquidificador Oster Aço Escovado',
    description: 'O clássico Osterizer 1.25L para nossa cozinha.',
    category: 'Eletrodomésticos',
    totalAmount: 650,
    currentAmount: 0,
    imageUrl: '/img/3.jpg',
  },
  {
    id: '4',
    name: 'Faqueiro Wolff Berna 48 peças',
    description: 'Lindo faqueiro em aço inox.',
    category: 'Cozinha',
    totalAmount: 330,
    currentAmount: 0,
    imageUrl: '/img/4.jpg',
  },
  {
    id: '5',
    name: 'Jogo de banho Buddemeyer Branco',
    description: 'Conjunto Lollipop Branco 5 peças.',
    category: 'Quarto e Banho',
    totalAmount: 300,
    currentAmount: 0,
    imageUrl: '/img/5.jpg',
  },
  {
    id: '6',
    name: 'Jogo de banho Buddemeyer Rosa',
    description: 'Conjunto Lollipop Rosa 5 peças.',
    category: 'Quarto e Banho',
    totalAmount: 330,
    currentAmount: 0,
    imageUrl: '/img/6.jpg',
  },
  {
    id: '7',
    name: 'Jogo de banho Buddemeyer Azul Marinho',
    description: 'Conjunto Lollipop Azul Marinho 5 peças.',
    category: 'Quarto e Banho',
    totalAmount: 330,
    currentAmount: 0,
    imageUrl: '/img/7.jpg',
  },
  {
    id: '8',
    name: 'Jogo de taças para vinho Haus',
    description: 'Taças de cristal 450ml 6 peças.',
    category: 'Cozinha',
    totalAmount: 120,
    currentAmount: 0,
    imageUrl: '/img/8.jpg',
  },
  {
    id: '9',
    name: 'Jogo de taças para champanhe Bohemia',
    description: 'Taças de cristal 250ml 6 peças.',
    category: 'Cozinha',
    totalAmount: 190,
    currentAmount: 0,
    imageUrl: '/img/9.jpg',
  },
  {
    id: '10',
    name: 'Conjunto de taças para cerveja Ruvolo',
    description: 'Royal Beer 330ml 6 peças.',
    category: 'Cozinha',
    totalAmount: 140,
    currentAmount: 0,
    imageUrl: '/img/10.jpg',
  },
  {
    id: '11',
    name: 'Conjunto 5 potes de vidro hermético',
    description: 'Para organização da nossa despensa.',
    category: 'Cozinha',
    totalAmount: 150,
    currentAmount: 0,
    imageUrl: '/img/11.jpg',
  },
  {
    id: '12',
    name: 'Conjunto de panelas Tramontina Allegra',
    description: '7 peças em aço inox para nossas receitas.',
    category: 'Cozinha',
    totalAmount: 700,
    currentAmount: 0,
    imageUrl: '/img/12.jpg',
  },
  {
    id: '13',
    name: 'Conjunto de facas Special Cut',
    description: 'Para um corte perfeito na cozinha.',
    category: 'Cozinha',
    totalAmount: 150,
    currentAmount: 0,
    imageUrl: '/img/13.jpg',
  },
  {
    id: '14',
    name: 'Jogo de utensílios Extrata aço inox',
    description: 'Para nos auxiliar no preparo dos pratos.',
    category: 'Cozinha',
    totalAmount: 200,
    currentAmount: 0,
    imageUrl: '/img/14.jpg',
  },
  {
    id: '15',
    name: 'Abridor de latas Kitchen Mama',
    description: 'Orbit One recarregável, muita praticidade.',
    category: 'Cozinha',
    totalAmount: 490,
    currentAmount: 0,
    imageUrl: '/img/15.jpg',
  },
  {
    id: '16',
    name: 'Cafeteira Nespresso Vertuo Pop',
    description: 'Para começarmos o dia com um bom café.',
    category: 'Eletrodomésticos',
    totalAmount: 650,
    currentAmount: 0,
    imageUrl: '/img/16.jpg',
  },
  {
    id: '17',
    name: 'Mini Grill Oster 2 em 1 220v',
    description: 'Lanches rápidos e saborosos.',
    category: 'Eletrodomésticos',
    totalAmount: 150,
    currentAmount: 0,
    imageUrl: '/img/17.jpg',
  },
  {
    id: '18',
    name: 'Lava e Seca Smart LG 11kg inox',
    description: 'Nossa super aliada na lavanderia.',
    category: 'Eletrodomésticos',
    totalAmount: 5000,
    currentAmount: 0,
    imageUrl: '/img/18.jpg',
  },
  {
    id: '19',
    name: 'Ar-condicionado Split LG Inverter',
    description: 'Smart Voice IA 12.000 BTUs 220v.',
    category: 'Eletrodomésticos',
    totalAmount: 2250,
    currentAmount: 0,
    imageUrl: '/img/19.jpg',
  },
  {
    id: '20',
    name: 'Ferro de passar Black+Decker 220v',
    description: 'Para deixar nossas roupas impecáveis.',
    category: 'Eletrodomésticos',
    totalAmount: 190,
    currentAmount: 0,
    imageUrl: '/img/20.jpg',
  },
  {
    id: '21',
    name: 'Smart TV LG UHD 4K 55 polegadas',
    description: 'Para nossas sessões de cinema em casa.',
    category: 'Tecnologia',
    totalAmount: 2500,
    currentAmount: 0,
    imageUrl: '/img/21.jpg',
  },
  {
    id: '22',
    name: 'Cafeteira Oster com jarra térmica',
    description: 'Em inox, mantém o café quentinho por mais tempo.',
    category: 'Eletrodomésticos',
    totalAmount: 220,
    currentAmount: 0,
    imageUrl: '/img/22.jpg',
  },
  {
    id: '23',
    name: 'Edredom Queen Karsten 300 fios',
    description: '100% algodão para noites confortáveis.',
    category: 'Quarto e Banho',
    totalAmount: 800,
    currentAmount: 0,
    imageUrl: '/img/23.jpg',
  },
  {
    id: '24',
    name: 'Toalha banhão Karsten branca',
    description: 'Fio penteado, extrema maciez.',
    category: 'Quarto e Banho',
    totalAmount: 200,
    currentAmount: 0,
    imageUrl: '/img/24.jpg',
  },
  {
    id: '25',
    name: 'Toalha banhão Karsten bege',
    description: 'Fio penteado, extrema maciez.',
    category: 'Quarto e Banho',
    totalAmount: 200,
    currentAmount: 0,
    imageUrl: '/img/25.jpg',
  },
  {
    id: '26',
    name: 'Jogo de cama Queen Karsten 300 fios',
    description: '100% algodão, requinte para nosso quarto.',
    category: 'Quarto e Banho',
    totalAmount: 500,
    currentAmount: 0,
    imageUrl: '/img/26.jpg',
  },
  {
    id: '27',
    name: 'Colcha Queen microfibra Karsten',
    description: 'Conforto e beleza para a cama.',
    category: 'Quarto e Banho',
    totalAmount: 400,
    currentAmount: 0,
    imageUrl: '/img/27.jpg',
  },
  {
    id: '28',
    name: 'Roupão Karsten 100% algodão',
    description: 'Para relaxarmos após o banho.',
    category: 'Quarto e Banho',
    totalAmount: 400,
    currentAmount: 0,
    imageUrl: '/img/28.jpg',
  },
  {
    id: '29',
    name: 'JBL Boombox 4',
    description: 'Para animar nossas festas e encontros.',
    category: 'Tecnologia',
    totalAmount: 2400,
    currentAmount: 0,
    imageUrl: '/img/29.jpg',
  },
  {
    id: '30',
    name: 'Robô aspirador Xiaomi Robot Vacuum',
    description: 'Para manter nossa casa sempre limpa.',
    category: 'Casa',
    totalAmount: 1500,
    currentAmount: 0,
    imageUrl: '/img/30.jpg',
  },
  {
    id: '31',
    name: 'Difusor de ambientes Granado',
    description: 'Para deixar a casa sempre perfumada.',
    category: 'Casa',
    totalAmount: 180,
    currentAmount: 0,
    imageUrl: '/img/31.jpg',
  },
  {
    id: '32',
    name: 'Aspirador vertical de pó 220v',
    description: 'Praticidade na limpeza do dia a dia.',
    category: 'Eletrodomésticos',
    totalAmount: 200,
    currentAmount: 0,
    imageUrl: '/img/32.jpg',
  },
  {
    id: '33',
    name: 'Purificador de água Electrolux',
    description: 'Com refrigeração, saúde para nossa família.',
    category: 'Eletrodomésticos',
    totalAmount: 600,
    currentAmount: 0,
    imageUrl: '/img/33.jpg',
  },
  {
    id: '34',
    name: 'Caldeirão Tramontina Allegra inox',
    description: '7,5L para grandes receitas.',
    category: 'Cozinha',
    totalAmount: 450,
    currentAmount: 0,
    imageUrl: '/img/34.jpg',
  },
  {
    id: '35',
    name: 'Panela de pressão Rochedo inox 6L',
    description: 'Mais segurança e rapidez no preparo.',
    category: 'Cozinha',
    totalAmount: 300,
    currentAmount: 0,
    imageUrl: '/img/35.jpg',
  },
  {
    id: '36',
    name: 'Micro-ondas Mondial 21L espelhado',
    description: 'Design e praticidade para a cozinha.',
    category: 'Eletrodomésticos',
    totalAmount: 600,
    currentAmount: 0,
    imageUrl: '/img/36.jpg',
  },
  {
    id: '37',
    name: 'Cooktop Suggar vidro preto 4 bocas',
    description: 'Elegância e eficiência em aço inox e vidro.',
    category: 'Eletrodomésticos',
    totalAmount: 630,
    currentAmount: 0,
    imageUrl: '/img/37.jpg',
  },
  {
    id: '38',
    name: 'Chaleira elétrica inox',
    description: 'Água quente em minutos.',
    category: 'Eletrodomésticos',
    totalAmount: 150,
    currentAmount: 0,
    imageUrl: '/img/38.jpg',
  },
  {
    id: '39',
    name: 'Forno de embutir elétrico Oster',
    description: 'Para os nossos melhores assados.',
    category: 'Eletrodomésticos',
    totalAmount: 2000,
    currentAmount: 0,
    imageUrl: '/img/39.jpg',
  },
  {
    id: '40',
    name: 'Caixa térmica cooler 32L',
    description: 'Para nossas viagens e passeios.',
    category: 'Casa',
    totalAmount: 130,
    currentAmount: 0,
    imageUrl: '/img/40.jpg',
  },
  {
    id: '41',
    name: 'Jantar Romântico no NAU',
    description: 'Celebração com Frutos do Mar no restaurante NAU.',
    category: 'Experiências',
    totalAmount: 800,
    currentAmount: 0,
    imageUrl: '/img/41.jpg',
  }
];
