import { Gift } from '../types';

export const GIFTS_DATA: Gift[] = [
  {
    id: '1',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 800,
    currentAmount: 0,
    imageUrl: '/img/LOGO_MARCA.jpg',
  },
  {
    id: '2',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 800,
    currentAmount: 0,
    imageUrl: '/img/LOGO_MARCA.jpg',
  },
  {
    id: '3',
    name: 'Edredom Queen',
    description: 'Para noites confortáveis',
    category: 'Quarto e Banho',
    totalAmount: 800,
    currentAmount: 0,
    imageUrl: '/img/23.jpg',
  },
  {
    id: '4',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 900,
    currentAmount: 0,
    imageUrl: '/img/LOGO_MARCA.jpg',
  },
  {
    id: '5',
    name: 'Cotas LUA DE MEL',
    description: 'Contribuição para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 900,
    currentAmount: 0,
    imageUrl: '/img/LOGO_MARCA.jpg',
  },
  {
    id: '6',
    name: 'Chopeira',
    description: 'Para nossos momentos de lazer',
    category: 'Eletrodomésticos',
    totalAmount: 949,
    currentAmount: 0,
    imageUrl: '/img/10.jpg',
  },
  {
    id: '7',
    name: 'Mala para viagem',
    description: 'Para nossa lua de mel',
    category: 'Experiências',
    totalAmount: 1000,
    currentAmount: 0,
    imageUrl: '/img/40.jpg',
  },
  {
    id: '8',
    name: 'Persiana',
    description: 'Para nossa casa',
    category: 'Casa',
    totalAmount: 1200,
    currentAmount: 0,
    imageUrl: '/img/LOGO_MARCA.jpg',
  },
  {
    id: '9',
    name: 'Aparelho de Jantar',
    description: 'Para nossas refeições',
    category: 'Cozinha',
    totalAmount: 1400,
    currentAmount: 0,
    imageUrl: '/img/4.jpg',
  },
  {
    id: '10',
    name: 'Robo aspirador de Pó',
    description: 'Para manter nossa casa limpa',
    category: 'Eletrodomésticos',
    totalAmount: 1500,
    currentAmount: 0,
    imageUrl: '/img/30.jpg',
  },
  {
    id: '11',
    name: 'Kit sobrevivência do casal',
    description: 'Para os momentos importantes',
    category: 'Casa',
    totalAmount: 1621,
    currentAmount: 0,
    imageUrl: '/img/LOGO_MARCA.jpg',
  },
  {
    id: '12',
    name: 'Home Theater',
    description: 'Para nossa sala de TV',
    category: 'Tecnologia',
    totalAmount: 1630,
    currentAmount: 0,
    imageUrl: '/img/21.jpg',
  },
  {
    id: '13',
    name: 'Lava louças',
    description: 'Praticidade na cozinha',
    category: 'Eletrodomésticos',
    totalAmount: 1690,
    currentAmount: 0,
    imageUrl: '/img/36.jpg',
  },
  {
    id: '14',
    name: 'Cervejeira',
    description: 'Para as bebidas sempre geladas',
    category: 'Eletrodomésticos',
    totalAmount: 1850,
    currentAmount: 0,
    imageUrl: '/img/10.jpg',
  },
  {
    id: '15',
    name: 'Forno de Embutir elétrico',
    description: 'Para nossos assados',
    category: 'Eletrodomésticos',
    totalAmount: 2000,
    currentAmount: 0,
    imageUrl: '/img/39.jpg',
  },
  {
    id: '16',
    name: 'Jbl boombox',
    description: 'Para animar nossas festas',
    category: 'Tecnologia',
    totalAmount: 2200,
    currentAmount: 0,
    imageUrl: '/img/29.jpg',
  },
  {
    id: '17',
    name: 'Ar-condicionado',
    description: 'Para o nosso conforto',
    category: 'Eletrodomésticos',
    totalAmount: 2250,
    currentAmount: 0,
    imageUrl: '/img/19.jpg',
  },
  {
    id: '18',
    name: 'Smart TV 55 polegadas',
    description: 'Para nossos filmes e séries',
    category: 'Tecnologia',
    totalAmount: 2500,
    currentAmount: 0,
    imageUrl: '/img/21.jpg',
  },
  {
    id: '19',
    name: 'Mesa de Jantar',
    description: 'Para reunir a família',
    category: 'Casa',
    totalAmount: 2800,
    currentAmount: 0,
    imageUrl: '/img/LOGO_MARCA.jpg',
  },
  {
    id: '20',
    name: 'Cama Queen',
    description: 'Para nosso descanso',
    category: 'Quarto e Banho',
    totalAmount: 3400,
    currentAmount: 0,
    imageUrl: '/img/26.jpg',
  },
  {
    id: '21',
    name: 'Sofa',
    description: 'Para nossa sala',
    category: 'Casa',
    totalAmount: 3500,
    currentAmount: 0,
    imageUrl: '/img/LOGO_MARCA.jpg',
  },
  {
    id: '22',
    name: 'Geladeira',
    description: 'Para nossa cozinha',
    category: 'Eletrodomésticos',
    totalAmount: 4100,
    currentAmount: 0,
    imageUrl: '/img/LOGO_MARCA.jpg',
  },
  {
    id: '23',
    name: 'Maquina Lava e Seca',
    description: 'Para nossa lavanderia',
    category: 'Eletrodomésticos',
    totalAmount: 5000,
    currentAmount: 0,
    imageUrl: '/img/18.jpg',
  }
];
